$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  resources:
    type: string
    description: path to resources.yaml file
  samples:
    type: string
    description: path to samples.tsv file
  units:
    type: string
    description: path to units.tsv file
  default_container:
    type: string
    description: name or path to a default docker/singularity container
  reference:
    type: object
    properties:
      fasta:
        type: string
        description: fasta reference file
      design_intervals:
        type: string
        description: picard style bed file for design regions
      design_bed:
        type: string
        description: bed file for design regions
      hotspots:
        type: string
        description: file listing all hotspot positions
      background:
        type: string
        description: background info for all positions in design
    required:
      - fasta

  fastqc:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for fastqc
      container:
        type: string
        description: name or path to docker/singularity container
      outdir:
        type: string
        description: path to outdir directory
      tmp:
        type: string
        description: path to temporary directory

  hotspot_info:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for hotspot_info
      container:
        type: string
        description: name or path to docker/singularity container
      min_coverage:
        type: integer
        description: coverage under which hotspot positions should be reported

  mosdepth:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for fastqc
      by:
        type: string
        description: by flag passed to mosdepth
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra flags passed to mosdepth

  multiqc:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for fastqc
      container:
        type: string
        description: name or path to docker/singularity container
      config:
        type: string
        description: path to multiqc_config.yaml
      extra:
        type: string
        description: extra parameters to multiqc
      qc_files:
        type: array
        items:
            type: string
        description: list with path to qc-files that will be used to generate a MultiQC report.
    required:
      - qc_files

  picard_alignment_summary_metrics:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for picard_alignment_summary_metrics
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters to picard_alignment_summary_metrics

  picard_collect_gc_bias_metrics:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for 'picard_collect_gc_bias_metrics'
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters to 'picard_collect_gc_bias_metrics'

  picard_collect_multiple_metrics:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for 'picard_collect_multiple_metrics'
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters to 'picard_collect_multiple_metrics'
      output_ext:
        type: array
        items:
          type: string
        description: output file extensions for 'picard_collect_multiple_metrics'

  picard_collect_wgs_metrics:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for 'picard_collect_wgs_metrics'
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters to 'picard_collect_wgs_metrics'

  picard_duplication_metrics:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for picard_duplication_metrics
      container:
        type: string
        description: name or path to docker/singularity container

  picard_collect_hs_metrics:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for picard_collect_hs_metrics
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters to picard_collect_hs_metrics

  picard_insert_size:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for picard_insert_size
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters to picard_insert_size

  samtools_stats:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for samtools_stats
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters to samtools_stats

  required:
    - samples
    - units
    - resources
    - default_container
    - multiqc
