resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://gmsuppsala/somatic:develop"

reference:
  fasta: "reference/HES45.fna"
  design_intervals: "reference/twist_DNA_solid.HES45.annotated.interval_list"

fastqc:
  container: "docker://hydra/fastqc:0.11.9"
