resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

reference:
  fasta: "reference/HES45.fna"
  design_intervals: "reference/twist_DNA_solid.HES45.annotated.interval_list"
  design_bed: "reference/twist_DNA_solid.HES45.annotated.bed"
  hotspots: "reference/hotspots_small.csv"
  background: "reference/background_panel_small.tsv"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

samtools_stats:
  container: "docker://hydragenetics/common:0.0.1"

picard_alignment_summary_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_duplication_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_hs_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_insert_size:
  container: "docker://hydragenetics/picard:2.25.0"

hotspot_info:
  container: "docker://hydragenetics/common:0.0.1"
