resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

reference:
  fasta: "reference/HES45.fna"
  design_intervals: "reference/twist_DNA_solid.HES45.annotated.interval_list"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"
