resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

reference:
  fasta: "reference/HES45.fna"
  design_intervals: "reference/twist_DNA_solid.HES45.annotated.interval_list"
  design_bed: "reference/twist_DNA_solid.HES45.annotated.bed"
  hotspots: "reference/hotspots_small.csv"
  background: "reference/background_panel_small.tsv"
  wgs_intervals: "reference/twist_DNA_solid.HES45.annotated.interval_list"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

hotspot_info:
  container: "docker://hydragenetics/common:0.0.1"

mosdepth:
  by: "500"
  container: "docker://hydragenetics/mosdepth:0.3.2"
  extra: "--fast-mode --no-per-base"

multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  qc_files:
    - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
    - "qc/picard_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
    - "qc/fastqc/{sample}_{type}_fastq1_fastqc.zip"
    - "qc/fastqc/{sample}_{type}_fastq2_fastqc.zip"
    - "qc/picard_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
    - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"

picard_alignment_summary_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_gc_bias_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_multiple_metrics:
  container: "docker://hydragenetics/picard:2.25.0"
  output_ext:
    - "gc_bias.pdf"

picard_collect_wgs_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_duplication_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_hs_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_insert_size:
  container: "docker://hydragenetics/picard:2.25.0"

samtools_stats:
  container: "docker://hydragenetics/common:0.0.1"

hotspot_info:
  container: "docker://hydragenetics/common:0.0.1"
